yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Название группы',
                             help_text='Максимум 200 символов', max_length=200)
    slug = models.SlugField('уникальный адрес',
                            help_text='Обязательное поле.', unique=True)
    description = models.TextField('Описание сообщества')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField('Tекст поста')
    pub_date = models.DateTimeField('Дата и время', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Имя автора'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Сообщество'
    )

    class Meta:
        ordering = ('-pub_date',)

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render

from .models import Group, Post


def index(request):
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:10]
    context = {
        'group': group,
        'posts': posts,

    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" type="image" href="{% static 'img/fav/favicon.ico' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <header>
      <!-- Это тег шаблонизатора include, сюда будет включён код
      из файла includes/header.html -->
      {% include 'includes/header.html' %}
    </header>
    <main>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        {% block content %}{% endblock %}
      </div>
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
  <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
  <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
<!-- В дальнейшем тут будет создано полноценное меню -->
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static "img/logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
      <span style="color:red">Ya</span>tube
    </a>
  </div>
</nav>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}Записи сообщества {{ group.title }}{% endblock title %}

{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in posts %}
    <article>
      <ul>
        <li>Автор: {{ post.author.get_full_name }}</li>
        <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
      </ul>
      <p>{{ post.text|linebreaksbr }}</p>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}Последние обновления на сайте{% endblock %}

{% block content %}
  <h1>Последние обновления на сайте</h1>
  {% for post in posts %}
    <article>
      <ul>
        <li>Автор: {{ post.author.get_full_name }}</li>
        <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
      </ul>
      <p>{{ post.text|linebreaksbr }}</p>
      {% if post.group %}
          Группа: <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a>
      {% endif %}
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endblock %}